spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          jdbc-url: jdbc:mysql://localhost:3306/tsim?useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: admin
        secondary:
          jdbc-url: jdbc:mysql://localhost:3306/nxdb?useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    locale: zh_CN
    default-property-inclusion: non_empty
  servlet:
    multipart:
      max-request-size: 5GB # 上传文件总的最大值
      max-file-size: 1GB # 单个文件最大值
# 开启mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  servlet:
    session:
      timeout: 7200  # session时长
  port: 1024  # 端口测试

file:
  upload-dir: ./upload
  selenium-screenshots: ./selenium-screenshots  # 测试用例执行失败后自动截图存放文件夹

webdriver:
  isRemote: false
  browser: CHROME
  service:
    location: http://localhost
    port: 4444
    default-username: admin
    default-password: 123456
    test-server: http://39.103.139.6:9004/
  capabilities:
    javascriptEnabled: true
    takeScreenshot: true
    browserName: chrome