-- auto Generated on 2021-10-18
-- DROP TABLE IF EXISTS test_bug;
CREATE TABLE test_bug(
	id VARCHAR (50) NOT NULL COMMENT '主键id',
	project_id VARCHAR (50) NOT NULL DEFAULT '' COMMENT '项目id',
	module_id VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'suite id',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT '标题',
	severity VARCHAR (50) NOT NULL DEFAULT '' COMMENT '严重程度(1:轻微,2:一般,3:严重,4:致命)',
	func VARCHAR (50) NOT NULL DEFAULT '' COMMENT '功能点',
	bug_status VARCHAR (50) NOT NULL DEFAULT '' COMMENT '状态',
	note VARCHAR (50) NOT NULL DEFAULT '' COMMENT '备注内容',
	tester VARCHAR (50) NOT NULL DEFAULT '' COMMENT '测试人员',
	work_date VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'workDate',
	plan_id VARCHAR (50) NOT NULL DEFAULT '' COMMENT '测试计划id',
	create_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	update_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '修改时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '问题单(bug)表';
